name: docker_ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
     -

       name: simple echo
       run: echo main
     - 
     #  name: simple echo
     #  uses: actions/checkout@v3
     # -
     #  name: login to docker hub
     #  uses: docker/login-actions@v2
     #  with:
     #    username: ${{secrets....}}
     #    password: ${{secrerts ....}}
     # -
     #  name:set up docker build
     #  uses:docker/build 
